CREATE TABLE STUDENT
(
  SID INT,
  SNAME VARCHAR(25),
  DOB DATE,
  PHYSICS INT,
  CHEMISTRY INT,
  MATHS INT
);
INSERT INTO STUDENT(SID,SNAME,DOB,PHYSICS,CHEMISTRY,MATHS)VALUES
(100,'tom','1998-05-01',60,90,30),
(101,'jerry','2000-09-08',50,85,50),
(102,'jinse','1998-07-06',60,96,100),
(103,'amal','2002-03-18',100,60,35),
(104,'sanju','1998-04-01',50,65,70);
SELECT*FROM STUDENT;
SELECT SID,SNAME AS YOUNGEST_STUDENT, DOB AS DATE_OF_BIRTH FROM STUDENT WHERE DOB=(SELECT MAX(DOB)FROM STUDENT);
SELECT*FROM STUDENT WHERE (PHYSICS OR CHEMISTRY) AND MATHS >=40;
ALTER TABLE STUDENT ADD COLUMN(TOTAL INT,AVERAGE INT);
DESCRIBE STUDENT;
SELECT SNAME, MATHS AS MAX_MARK_OF_MATHS FROM STUDENT WHERE MATHS=(SELECT MAX(MATHS)FROM STUDENT);
SELECT SNAME, CHEMISTRY AS MIN_MARK_OF_CHEMISTRY FROM STUDENT WHERE CHEMISTRY=(SELECT MIN(CHEMISTRY)FROM STUDENT);
UPDATE STUDENT SET TOTAL=PHYSICS+CHEMISTRY+MATHS;
SELECT * FROM STUDENT ORDER BY TOTAL DESC;
ALTER TABLE STUDENT CHANGE AVERAGE AVERAGE_MARK INT;
SELECT AVG(TOTAL/5) AS OVERALL_AVERAGE FROM STUDENT;
UPDATE STUDENT SET AVERAGE_MARK=(PHYSICS+CHEMISTRY+MATHS)/3;
SELECT * FROM STUDENT WHERE AVERAGE_MARK > 40.04000000;
SELECT COUNT(*)FROM STUDENT WHERE AVERAGE_MARK > 40.04000000;